---
# Based on: https://github.com/AlexNabokikh/windows-playbook/blob/8be81399018d151e5f4f5ea08034fc4bd0ad30da/tasks/start_menu.yml

- name: Ensure App Suggestions in Start menu disabled for win_startmenu_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword
  loop: "{{ win_startmenu_users }}"

- name: Ensure App Suggestions in Start menu disabled  for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword
  when: win_startmenu_also_for_ansible_user | bool

- name: Ensure Bing search is disabled in Start menu disabled for win_startmenu_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Policies\Microsoft\Windows\Explorer
    name: DisableSearchBoxSuggestions
    data: 1
    type: dword
  loop: "{{ win_startmenu_users }}"

- name: Ensure Bing search is disabled in Start menu disabled for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Policies\Microsoft\Windows\Explorer
    name: DisableSearchBoxSuggestions
    data: 1
    type: dword
  when: win_startmenu_also_for_ansible_user | bool

- name: Ensure popup "tips" about Windows disabled for win_startmenu_users
  ansible.windows.win_regedit:
    hive: "C:\\Users\\{{ item }}\\NTUSER.dat"
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword
  loop: "{{ win_startmenu_users }}"

- name: Ensure popup "tips" about Windows disabled for ansible_user
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword
  when: win_startmenu_also_for_ansible_user | bool
